# Copyright 2017 The Openstack-Helm Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Default values for keystone.
# This is a YAML-formatted file.
# Declare name/value pairs to be passed into your templates.
# name: value

replicas:
  api: 1
  volume: 1
  scheduler: 1

labels:
  node_selector_key: openstack-control-plane
  node_selector_value: enabled

images:
  dep_check: quay.io/stackanetes/kubernetes-entrypoint:v0.1.0
  ks_user: quay.io/stackanetes/stackanetes-kolla-toolbox:newton
  ks_service: quay.io/stackanetes/stackanetes-kolla-toolbox:newton
  ks_endpoints: quay.io/stackanetes/stackanetes-kolla-toolbox:newton
  db_init: quay.io/stackanetes/stackanetes-kolla-toolbox:newton
  db_sync: quay.io/stackanetes/stackanetes-cinder-api:newton
  api: quay.io/stackanetes/stackanetes-cinder-api:newton
  scheduler: quay.io/stackanetes/stackanetes-cinder-scheduler:newton
  volume: quay.io/stackanetes/stackanetes-cinder-volume:newton
  pull_policy: "IfNotPresent"

upgrades:
  revision_history: 3
  pod_replacement_strategy: RollingUpdate
  rolling_update:
    max_unavailable: 1
    max_surge: 3

keystone:
  auth_uri: "http://keystone-api:5000"
  auth_url: "http://keystone-api:35357"
  admin_user: "admin"
  admin_user_domain: "default"
  admin_password: "password"
  admin_project_name: "admin"
  admin_project_domain: "default"
  admin_region_name: "RegionOne"

  cinder_user: "cinder"
  cinder_user_domain: "default"
  cinder_user_role: "admin"
  cinder_password: "password"
  cinder_project_name: "service"
  cinder_project_domain: "default"
  cinder_region_name: "RegionOne"

service:
  api:
    name: "cinder-api"
    port: 8776
    proto: "http"

database:
  address: mariadb
  port: 3306
  root_user: root
  root_password: password
  cinder_database_name: cinder
  cinder_password: password
  cinder_user: cinder

ceph:
  enabled: true
  monitors: []
  cinder_user: "admin"
  # a null value for the keyring will
  # attempt to use the key from
  # common/secrets/ceph-client-key
  cinder_keyring: null

backends:
  enabled:
  - rbd1
  rbd1:
    secret: null
    user: "admin"
    pool: "volumes"

glance:
  proto: "http"
  host: "glance-api"
  port: 9292
  version: 2

messaging:
  hosts: rabbitmq
  user: rabbitmq
  password: password


api:
  workers: 8

misc:
  debug: false

dependencies:
  db_init:
    jobs:
    - mariadb-seed
    service:
    - mariadb
  db_sync:
    jobs:
    - cinder-db-init
    service:
    - mariadb
  ks_user:
    service:
    - keystone-api
  ks_service:
    service:
    - keystone-api
  ks_endpoints:
    jobs:
    - cinder-ks-service
    service:
    - keystone-api
  api:
    jobs:
    - cinder-db-sync
    - cinder-ks-user
    - cinder-ks-endpoints
    service:
    - mariadb
    - keystone-api
  volume:
    jobs:
    - cinder-db-sync
    - cinder-ks-user
    - cinder-ks-endpoints
    service:
    - keystone-api
    - cinder-api
  scheduler:
    jobs:
    - cinder-db-sync
    - cinder-ks-user
    - cinder-ks-endpoints
    service:
    - keystone-api
    - cinder-api

# We use a different layout of the endpoints here to account for versioning
# this swaps the service name and type, and should be rolled out to other
# services.
endpoints:
  identity:
    name: keystone
    hosts:
      default: keystone-api
    path: /v3
    scheme: 'http'
    port:
        admin: 35357
        public: 5000
  volume:
    name: cinder
    hosts:
      default: cinder-api
    path: '/v1/%(tenant_id)s'
    scheme: 'http'
    port:
      api: 8776
  volumev2:
    name: cinder
    hosts:
      default: cinder-api
    path: '/v2/%(tenant_id)s'
    scheme: 'http'
    port:
      api: 8776
  volumev3:
    name: cinder
    hosts:
      default: cinder-api
    path: '/v3/%(tenant_id)s'
    scheme: 'http'
    port:
      api: 8776

resources:
  enabled: false
  cinder_api:
    requests:
      memory: "124Mi"
      cpu: "100m"
    limits:
      memory: "1024Mi"
      cpu: "2000m"
  cinder_scheduler:
    requests:
      memory: "124Mi"
      cpu: "100m"
    limits:
      memory: "1024Mi"
      cpu: "2000m"
  cinder_volume:
    requests:
      memory: "124Mi"
      cpu: "100m"
    limits:
      memory: "1024Mi"
      cpu: "2000m"
  cinder_db_init:
    requests:
      memory: "124Mi"
      cpu: "100m"
    limits:
      memory: "1024Mi"
      cpu: "2000m"
  cinder_db_sync:
    requests:
      memory: "124Mi"
      cpu: "100m"
    limits:
      memory: "1024Mi"
      cpu: "2000m"
  cinder_ks_endpoints:
    requests:
      memory: "124Mi"
      cpu: "100m"
    limits:
      memory: "1024Mi"
      cpu: "2000m"
  cinder_ks_service:
    requests:
      memory: "124Mi"
      cpu: "100m"
    limits:
      memory: "1024Mi"
      cpu: "2000m"
  cinder_ks_user:
    requests:
      memory: "124Mi"
      cpu: "100m"
    limits:
      memory: "1024Mi"
      cpu: "2000m"

