apiVersion: v1
kind: ConfigMap
metadata:
  name: glance-bin
data:
  init.sh: |+
{{ tuple "bin/_init.sh.tpl" . | include "helm-toolkit.template" | indent 4 }}
  post.sh: |+
{{ tuple "bin/_post.sh.tpl" . | include "helm-toolkit.template" | indent 4 }}
