{{- $envAll := . }}
{{- $dependencies := .Values.dependencies.post }}
apiVersion: batch/v1
kind: Job
metadata:
  name: glance-post
spec:
  template:
    metadata:
      annotations:
        pod.beta.kubernetes.io/init-containers: '[
{{ tuple $envAll $dependencies | include "helm-toolkit.kubernetes_entrypoint_init_container" | indent 10 }}
        ]'
    spec:
      nodeSelector:
        {{ .Values.labels.node_selector_key }}: {{ .Values.labels.node_selector_value }}
      restartPolicy: OnFailure
      containers:
        - name: glance-post
          image: {{ .Values.images.post }}
          imagePullPolicy: {{ .Values.images.pull_policy }}
          {{- if .Values.resources.enabled }}
          resources:
            limits:
              cpu: {{ .Values.resources.jobs.post.limits.cpu | quote }}
              memory: {{ .Values.resources.jobs.post.limits.memory | quote }}
            requests:
              cpu: {{ .Values.resources.jobs.post.requests.cpu | quote }}
              memory: {{ .Values.resources.jobs.post.requests.memory | quote }}
          {{- end }}
          command:
            - bash
            - /tmp/post.sh
          volumeMounts:
            - name: postsh
              mountPath: /tmp/post.sh
              subPath: post.sh
          env:
          - name: ANSIBLE_LIBRARY
            value: /usr/share/ansible/
      volumes:
        - name: postsh
          configMap:
            name: glance-bin
