# Default values for memcached.
# This is a YAML-formatted file.
# Declare name/value pairs to be passed into your templates.
# name: value

images:
  memcached: docker.io/memcached:1.4
  pull_policy: "IfNotPresent"

upgrades:
  revision_history: 3
  pod_replacement_strategy: RollingUpdate
  rolling_update:
    max_unavailable: 1
    max_surge: 3

labels:
  node_selector_key: openstack-control-plane
  node_selector_value: enabled

network:
  port: 11211

memcached:
  memory: 1024
  max_connections: 8192

resources:
  enabled: false
  memcached:
    replicas: 1
  api:
    limits:
      memory: "128Mi"
      cpu: "500m"
    requests:
      memory: "128Mi"
      cpu: "500m"
