# Default values for horizon.
# This is a YAML-formatted file.
# Declare name/value pairs to be passed into your templates.
# name: value

replicas: 1

images:
  dep_check: quay.io/stackanetes/kubernetes-entrypoint:v0.1.0
  horizon: quay.io/stackanetes/stackanetes-horizon:newton
  pull_policy: "IfNotPresent"

upgrades:
  revision_history: 3
  pod_replacement_strategy: RollingUpdate
  rolling_update:
    max_unavailable: 1
    max_surge: 3

labels:
  node_selector_key: openstack-control-plane
  node_selector_value: enabled

network:
  port: 80
  node_port: 30000
  enable_node_port: false

local_settings:
  horizon_secret_key: 9aee62c0-5253-4a86-b189-e0fb71fa503c
  debug: "True"

dependencies:
  dashboard:
    service:
    - memcached
    - keystone-api

resources:
  enabled: false
  dashboard:
    limits:
      memory: "128Mi"
      cpu: "500m"
    requests:
      memory: "128Mi"
      cpu: "500m"

# mits:typically overriden by environmental 
# values, but should include all endpoints
# required by this chart
endpoints:
  keystone:
    hosts:
      default: keystone-api
    path: /v2.0
    type: identity
    scheme: 'http'
    port:
        admin: 35357
        public: 5000

