apiVersion: v1
kind: ConfigMap
metadata:
  name: heat-bin
data:
  db-init.sh: |+
{{ tuple "bin/_db-init.sh.tpl" . | include "helm-toolkit.template" | indent 4 }}
  ks-service.sh: |+
{{- include "helm-toolkit.keystone_service" . | indent 4 }}
  ks-endpoints.sh: |+
{{- include "helm-toolkit.keystone_endpoints" . | indent 4 }}
  ks-user.sh: |+
{{- include "helm-toolkit.keystone_user" . | indent 4 }}
  ks-domain-user.sh: |+
{{- include "helm-toolkit.keystone_domain_user" . | indent 4 }}
