{{- $envAll := . }}
{{- $dependencies := .Values.dependencies.api }}
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: heat-api
spec:
  replicas: {{ .Values.replicas.api }}
  template:
    metadata:
      labels:
        app: heat-api
      annotations:
        pod.beta.kubernetes.io/init-containers: '[
{{ tuple $envAll $dependencies | include "helm-toolkit.kubernetes_entrypoint_init_container" | indent 10 }}
        ]'
    spec:
      nodeSelector:
        {{ .Values.labels.node_selector_key }}: {{ .Values.labels.node_selector_value }}
      containers:
        - name: heat-api
          image: {{ .Values.images.api }}
          imagePullPolicy: {{ .Values.images.pull_policy }}
          {{- if .Values.resources.enabled }}
          resources:
            requests:
              memory: {{ .Values.resources.heat_api.requests.memory | quote }}
              cpu: {{ .Values.resources.heat_api.requests.cpu | quote }}
            limits:
              memory: {{ .Values.resources.heat_api.limits.memory | quote }}
              cpu: {{ .Values.resources.heat_api.limits.cpu | quote }}
          {{- end }}
          command:
            - heat-api
            - --config-dir
            - /etc/heat/conf
          ports:
            - containerPort: {{ .Values.service.api.port }}
          readinessProbe:
            tcpSocket:
              port: {{ .Values.service.api.port }}
          volumeMounts:
            - name: pod-etc-heat
              mountPath: /etc/heat
            - name: pod-var-cache-heat
              mountPath: /var/cache/heat
            - name: heatconf
              mountPath: /etc/heat/conf/heat.conf
              subPath: heat.conf
              readOnly: true
            - name: heatpaste
              mountPath: /etc/heat/api-paste.ini
              subPath: api-paste.ini
              readOnly: true
            - name: heatpolicy
              mountPath: /etc/heat/policy.json
              subPath: policy.json
              readOnly: true
      volumes:
        - name: pod-etc-heat
          emptyDir: {}
        - name: pod-var-cache-heat
          emptyDir: {}
        - name: heatconf
          configMap:
            name: heat-etc
        - name: heatpaste
          configMap:
            name: heat-etc
        - name: heatpolicy
          configMap:
            name: heat-etc
