{{- $envAll := . }}
{{- $dependencies := .Values.dependencies.init }}
apiVersion: batch/v1
kind: Job
metadata:
  name: heat-db-init
spec:
  template:
    metadata:
      annotations:
        pod.beta.kubernetes.io/init-containers: '[
{{ tuple $envAll $dependencies | include "helm-toolkit.kubernetes_entrypoint_init_container" | indent 10 }}
        ]'
    spec:
      restartPolicy: OnFailure
      nodeSelector:
        {{ .Values.labels.node_selector_key }}: {{ .Values.labels.node_selector_value }}
      containers:
        - name: heat-db-init
          image: {{ .Values.images.db_init | quote }}
          imagePullPolicy: {{ .Values.images.pull_policy | quote }}
          {{- if .Values.resources.enabled }}
          resources:
            requests:
              memory: {{ .Values.resources.heat_db_init.requests.memory | quote }}
              cpu: {{ .Values.resources.heat_db_init.requests.cpu | quote }}
            limits:
              memory: {{ .Values.resources.heat_db_init.limits.memory | quote }}
              cpu: {{ .Values.resources.heat_db_init.limits.cpu | quote }}
          {{- end }}
          env:
          - name: ANSIBLE_LIBRARY
            value: /usr/share/ansible/
          command:
            - bash
            - /tmp/db-init.sh
          volumeMounts:
            - name: dbinitsh
              mountPath: /tmp/db-init.sh
              subPath: db-init.sh
              readOnly: true
      volumes:
        - name: dbinitsh
          configMap:
            name: heat-bin
