{{- $envAll := . }}
{{- $dependencies := .Values.dependencies.db_sync }}
apiVersion: batch/v1
kind: Job
metadata:
  name: heat-db-sync
spec:
  template:
    metadata:
      annotations:
        pod.beta.kubernetes.io/init-containers: '[
{{ tuple $envAll $dependencies | include "helm-toolkit.kubernetes_entrypoint_init_container" | indent 10 }}
        ]'
    spec:
      restartPolicy: OnFailure
      nodeSelector:
        {{ .Values.labels.node_selector_key }}: {{ .Values.labels.node_selector_value }}
      containers:
        - name: heat-db-sync
          image: {{ .Values.images.db_sync }}
          imagePullPolicy: {{ .Values.images.pull_policy }}
          {{- if .Values.resources.enabled }}
          resources:
            requests:
              memory: {{ .Values.resources.heat_db_sync.requests.memory | quote }}
              cpu: {{ .Values.resources.heat_db_sync.requests.cpu | quote }}
            limits:
              memory: {{ .Values.resources.heat_db_sync.limits.memory | quote }}
              cpu: {{ .Values.resources.heat_db_sync.limits.cpu | quote }}
          {{- end }}
          command:
            - heat-manage
          args:
            - --config-dir
            - /etc/heat/conf
            - db_sync
          volumeMounts:
            - name: pod-etc-heat
              mountPath: /etc/heat
            - name: heatconf
              mountPath: /etc/heat/conf/heat.conf
              subPath: heat.conf
              readOnly: true
      volumes:
        - name: pod-etc-heat
          emptyDir: {}
        - name: heatconf
          configMap:
            name: heat-etc
