apiVersion: v1
kind: ConfigMap
metadata:
  name: keystone-etc
data:
  keystone.conf: |+
{{ tuple "etc/_keystone.conf.tpl" . | include "helm-toolkit.template" | indent 4 }}
  mpm_event.conf: |+
{{ tuple "etc/_mpm_event.conf.tpl" . | include "helm-toolkit.template" | indent 4 }}
  wsgi-keystone.conf: |+
{{ tuple "etc/_wsgi-keystone.conf.tpl" . | include "helm-toolkit.template" | indent 4 }}
  policy.json: |+
{{ tuple "etc/_policy.json.tpl" . | include "helm-toolkit.template" | indent 4 }}
  keystone-paste.ini: |+
{{ tuple "etc/_keystone-paste.ini.tpl" . | include "helm-toolkit.template" | indent 4 }}
  sso_callback_template.html: |+
{{ tuple "etc/_sso_callback_template.html.tpl" . | include "helm-toolkit.template" | indent 4 }}
