{{- $envAll := . }}
{{- $dependencies := .Values.dependencies.api }}
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: cinder-api
spec:
  replicas: {{ .Values.replicas.api }}
  revisionHistoryLimit: {{ .Values.upgrades.revision_history }}
  strategy:
    type: {{ .Values.upgrades.pod_replacement_strategy }}
    {{ if eq .Values.upgrades.pod_replacement_strategy "RollingUpdate" }}
    rollingUpdate:
      maxUnavailable: {{ .Values.upgrades.rolling_update.max_unavailable }}
      maxSurge: {{ .Values.upgrades.rolling_update.max_surge }}
    {{ end }}
  template:
    metadata:
      labels:
        app: cinder-api
      annotations:
        configmap-bin-hash: {{ tuple "configmap-bin.yaml" . | include "helm-toolkit.hash" }}
        configmap-etc-hash: {{ tuple "configmap-etc.yaml" . | include "helm-toolkit.hash" }}
        pod.beta.kubernetes.io/init-containers: '[
{{ tuple $envAll $dependencies | include "helm-toolkit.kubernetes_entrypoint_init_container" | indent 10 }}
        ]'
    spec:
      nodeSelector:
        {{ .Values.labels.node_selector_key }}: {{ .Values.labels.node_selector_value }}
      containers:
        - name: cinder-api
          image: {{ .Values.images.api }}
          imagePullPolicy: {{ .Values.images.pull_policy }}
          {{- if .Values.resources.enabled }}
          resources:
            requests:
              memory: {{ .Values.resources.cinder_api.requests.memory | quote }}
              cpu: {{ .Values.resources.cinder_api.requests.cpu | quote }}
            limits:
              memory: {{ .Values.resources.cinder_api.limits.memory | quote }}
              cpu: {{ .Values.resources.cinder_api.limits.cpu | quote }}
          {{- end }}
          command:
          - cinder-api
          - --config-dir
          - /etc/cinder/conf
          ports:
            - containerPort: {{ .Values.service.api.port }}
          readinessProbe:
            tcpSocket:
              port: {{ .Values.service.api.port }}
          volumeMounts:
            - name: pod-etc-cinder
              mountPath: /etc/cinder
            - name: pod-var-cache-cinder
              mountPath: /var/cache/cinder
            - name: cinderconf
              mountPath: /etc/cinder/conf/cinder.conf
              subPath: cinder.conf
              readOnly: true
            - name: cinderpaste
              mountPath: /etc/cinder/api-paste.ini
              subPath: api-paste.ini
              readOnly: true
            - name: cinderpolicy
              mountPath: /etc/cinder/policy.json
              subPath: policy.json
              readOnly: true
      volumes:
        - name: pod-etc-cinder
          emptyDir: {}
        - name: pod-var-cache-cinder
          emptyDir: {}
        - name: cinderconf
          configMap:
            name: cinder-etc
        - name: cinderpaste
          configMap:
            name: cinder-etc
        - name: cinderpolicy
          configMap:
            name: cinder-etc
