# Default values for rabbitmq.
# This is a YAML-formatted file.
# Declare name/value pairs to be passed into your templates.
# name: value

replicas: "1" # this must be quoted to deal with atoi

resources:
  enabled: false
  api:
    limits:
      memory: "128Mi"
      cpu: "500m"
    requests:
      memory: "128Mi"
      cpu: "500m"

labels:
  node_selector_key: openstack-control-plane
  node_selector_value: enabled
  
upgrades:
  revision_history: 3
  pod_replacement_strategy: RollingUpdate
  rolling_update:
    max_unavailable: 1
    max_surge: 3
auth:
  default_user: openstack
  default_pass: password
  admin_user: rabbitmq
  admin_pass: password

network:
  port:
    public: '5672'
    management: '15672'

images:
  rabbitmq: "rabbitmq:3-management"
