apiVersion: v1
kind: ConfigMap
metadata:
  name: maas-etc
data:
  named.conf.options: |+
{{ tuple "etc/_region-dns-config.tpl" . | include "helm-toolkit.template" | indent 4 }}
  secret: |
{{ tuple "etc/_secret.tpl" . | include "helm_toolkit.template" | indent 4 }}
  maas-region-controller.conf: |
{{ tuple "etc/_postgresql-config.tpl" . | include "helm_toolkit.template" | indent 4 }}
