apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.db_service_name }}
  labels:
    app: db-service
spec:
  ports:
  - port: {{ .Values.network.port.db_service }}
    targetPort: {{ .Values.network.port.db_service_target }}
    name: db-service
  selector:
    app: maas-region
