apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: memcached
spec:
  replicas: {{ .Values.resources.memcached.replicas }}
  revisionHistoryLimit: {{ .Values.upgrades.revision_history }}
  strategy:
    type: {{ .Values.upgrades.pod_replacement_strategy }}
    {{ if eq .Values.upgrades.pod_replacement_strategy "RollingUpdate" }}
    rollingUpdate:
      maxUnavailable: {{ .Values.upgrades.rolling_update.max_unavailable }}
      maxSurge: {{ .Values.upgrades.rolling_update.max_surge }}
    {{ end }}  
  template:
    metadata:
      labels:
        app: memcached
    spec:
      nodeSelector:
        {{ .Values.labels.node_selector_key }}: {{ .Values.labels.node_selector_value }}
      containers:
        - name: memcached
          image: {{ .Values.images.memcached }}
          imagePullPolicy: {{ .Values.images.pull_policy }}
          {{- if .Values.resources.enabled }}
          resources:
            limits:
              cpu: {{ .Values.resources.api.limits.cpu | quote }}
              memory: {{ .Values.resources.api.limits.memory | quote }}
            requests:
              cpu: {{ .Values.resources.api.requests.cpu | quote }}
              memory: {{ .Values.resources.api.requests.memory | quote }}
          {{- end }}
          command: ["sh", "-xec"]
          args:
            - |
              exec memcached -v \
                -p {{ .Values.network.port }} \
                -U 0 \
                -c {{ .Values.memcached.max_connections }} \
                -m {{ .Values.memcached.memory }};
          ports:
            - containerPort: {{ .Values.network.port }}
          readinessProbe:
            tcpSocket:
              port: {{ .Values.network.port }}
