apiVersion: v1
kind: ConfigMap
metadata:
  name: nova-etc
data:
  nova.conf: |+
{{ tuple "etc/_nova.conf.tpl" . | include "helm-toolkit.template" | indent 4 }}
  ceph.client.cinder.keyring.yaml: |+
{{ tuple "etc/_ceph.client.cinder.keyring.yaml.tpl" . | include "helm-toolkit.template" | indent 4 }}
  resolv.conf: |+
{{ tuple "etc/_resolv.conf.tpl" . | include "helm-toolkit.template" | indent 4 }}
  libvirtd.conf: |+
{{ tuple "etc/_libvirtd.conf.tpl" . | include "helm-toolkit.template" | indent 4 }}
