# Default values for utils.
# This is a YAML-formatted file.
# Declare name/value pairs to be passed into your templates.
# name: value

global:
  region: cluster
  tld: local

endpoints:
  fqdn: null

