apiVersion: v1
kind: ConfigMap
metadata:
  name: neutron-etc
data:
  dhcp-agent.ini: |
{{ tuple "etc/_dhcp-agent.ini.tpl" . | include "helm-toolkit.template" | indent 4 }}
  l3-agent.ini: |
{{ tuple "etc/_l3-agent.ini.tpl" . | include "helm-toolkit.template" | indent 4 }}
  metadata-agent.ini: |
{{ tuple "etc/_metadata-agent.ini.tpl" . | include "helm-toolkit.template" | indent 4 }}
  ml2-conf.ini: |
{{ tuple "etc/_ml2-conf.ini.tpl" . | include "helm-toolkit.template" | indent 4 }}
  neutron.conf: |
{{ tuple "etc/_neutron.conf.tpl" . | include "helm-toolkit.template" | indent 4 }}
  resolv.conf: |
{{ tuple "etc/_resolv.conf.tpl" . | include "helm-toolkit.template" | indent 4 }}
  dnsmasq.conf: ""
  