# Copyright 2017 The Openstack-Helm Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: v1
kind: ConfigMap
metadata:
  name: neutron-etc
data:
  dhcp-agent.ini: |
{{ tuple "etc/_dhcp-agent.ini.tpl" . | include "helm-toolkit.template" | indent 4 }}
  l3-agent.ini: |
{{ tuple "etc/_l3-agent.ini.tpl" . | include "helm-toolkit.template" | indent 4 }}
  metadata-agent.ini: |
{{ tuple "etc/_metadata-agent.ini.tpl" . | include "helm-toolkit.template" | indent 4 }}
  ml2-conf.ini: |
{{ tuple "etc/_ml2-conf.ini.tpl" . | include "helm-toolkit.template" | indent 4 }}
  neutron.conf: |
{{ tuple "etc/_neutron.conf.tpl" . | include "helm-toolkit.template" | indent 4 }}
  resolv.conf: |
{{ tuple "etc/_resolv.conf.tpl" . | include "helm-toolkit.template" | indent 4 }}
  dnsmasq.conf: ""
  
