{{- $envAll := . }}
{{- $dependencies := .Values.dependencies.ovs_agent }}
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: ovs-agent
spec:
  template:
    metadata:
      labels:
        app: ovs-agent
      annotations:
        configmap-bin-hash: {{ tuple "configmap-bin.yaml" . | include "helm-toolkit.hash" }}
        configmap-etc-hash: {{ tuple "configmap-etc.yaml" . | include "helm-toolkit.hash" }}
        pod.beta.kubernetes.io/init-containers: '[
{{ tuple $envAll $dependencies | include "helm-toolkit.kubernetes_entrypoint_init_container" | indent 10 }}
        ]'
    spec:
      nodeSelector:
        {{ .Values.labels.ovs.node_selector_key }}: {{ .Values.labels.ovs.node_selector_value }}
      securityContext:
        runAsUser: 0
      dnsPolicy: ClusterFirst
      hostNetwork: true
      containers:
        - name: ovs-agent
          image: {{ .Values.images.neutron_openvswitch_agent }}
          imagePullPolicy: {{ .Values.images.pull_policy }}
          {{- if .Values.resources.enabled }}
          resources:
            limits:
              cpu: {{ .Values.resources.ovs.agent.limits.cpu | quote }}
              memory: {{ .Values.resources.ovs.agent.limits.memory | quote }}
            requests:
              cpu: {{ .Values.resources.ovs.agent.requests.cpu | quote }}
              memory: {{ .Values.resources.ovs.agent.requests.memory | quote }}
          {{- end }}
          securityContext:
            privileged: true
          command:
            - bash
            - /tmp/neutron-openvswitch-agent.sh
          # ensures this container can can see a br-int
          # bridge before its marked as ready
          readinessProbe:
            exec:
              command:
                - bash
                - -c
                - 'ovs-vsctl list-br | grep -q br-int'
          volumeMounts:
            - name: neutronopenvswitchagentsh
              mountPath: /tmp/neutron-openvswitch-agent.sh
              subPath: neutron-openvswitch-agent.sh
            - name: neutronconf
              mountPath: /etc/neutron/neutron.conf
              subPath: neutron.conf
            - name: ml2confini
              mountPath: /etc/neutron/plugins/ml2/ml2-conf.ini
              subPath: ml2-conf.ini
            - name: libmodules
              mountPath: /lib/modules
              readOnly: true
            - name: run
              mountPath: /run
            - mountPath: /etc/resolv.conf
              name: resolvconf
              subPath: resolv.conf
      volumes:
        - name: varlibopenvswitch
          emptyDir: {}
        - name: neutronopenvswitchagentsh
          configMap:
            name: neutron-bin
        - name: neutronconf
          configMap:
            name: neutron-etc
        - name: ml2confini
          configMap:
            name: neutron-etc
        - name: resolvconf
          configMap:
            name: neutron-etc
        - name: libmodules
          hostPath:
            path: /lib/modules
        - name: run
          hostPath:
            path: /run
