{{- $envAll := . }}
{{- $dependencies := .Values.dependencies.db_sync }}
apiVersion: batch/v1
kind: Job
metadata:
  name: neutron-post
spec:
  template:
    metadata:
      annotations:
        pod.beta.kubernetes.io/init-containers: '[
{{ tuple $envAll $dependencies | include "helm-toolkit.kubernetes_entrypoint_init_container" | indent 10 }}
        ]'
    spec:
      restartPolicy: OnFailure
      nodeSelector:
        {{ .Values.labels.server.node_selector_key }}: {{ .Values.labels.server.node_selector_value }}
      containers:
        - name: neutron-post
          image: {{ .Values.images.post }}
          imagePullPolicy: {{ .Values.images.pull_policy }}
          command:
            - bash
            - /tmp/post.sh
          {{- if .Values.resources.enabled }}
          resources:
            limits:
              cpu: {{ .Values.resources.jobs.post.limits.cpu | quote }}
              memory: {{ .Values.resources.jobs.post.limits.memory | quote }}
            requests:
              cpu: {{ .Values.resources.jobs.post.requests.cpu | quote }}
              memory: {{ .Values.resources.jobs.post.requests.memory | quote }}
          {{- end }}
          env:
            - name: ANSIBLE_LIBRARY
              value: /usr/share/ansible/
          volumeMounts:
            - name: postsh
              mountPath: /tmp/post.sh
              subPath: post.sh
      volumes:
        - name: postsh
          configMap:
            name: neutron-bin
