# Copyright 2017 The Openstack-Helm Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: {{ .Values.service_name }}
spec:
  serviceName: "{{ .Values.service_name }}"
{{- if .Values.development.enabled }}
  replicas: 1
{{- else }}
  replicas: {{ .Values.replicas }}
{{- end }}
  template:
    metadata:
      labels:
        app: {{ .Values.service_name }}
        galera: enabled
      annotations:
        # alanmeadows: this soft requirement allows single
        # host deployments to spawn several mariadb containers
        # but in a larger environment, would attempt to spread
        # them out
        scheduler.alpha.kubernetes.io/affinity: >
          {
            "podAntiAffinity": {
              "preferredDuringSchedulingIgnoredDuringExecution": [{
                "labelSelector": {
                  "matchExpressions": [{
                    "key": "app",
                    "operator": "In",
                    "values":["mariadb"]
                  }]
                },
              "topologyKey": "kubernetes.io/hostname",
              "weight": 10
              }]
            }
          }
    spec:
      nodeSelector:
        {{ .Values.labels.node_selector_key }}: {{ .Values.labels.node_selector_value }}
      containers:
        - name: {{ .Values.service_name }}
          image: {{ .Values.images.mariadb }}
          imagePullPolicy: {{ .Values.images.pull_policy }}
          {{- if .Values.resources.enabled }}
          resources:
            limits:
              cpu: {{ .Values.resources.api.limits.cpu | quote }}
              memory: {{ .Values.resources.api.limits.memory | quote }}
            requests:
              cpu: {{ .Values.resources.api.requests.cpu | quote }}
              memory: {{ .Values.resources.api.requests.memory | quote }}
          {{- end }}
          env:
            - name: INTERFACE_NAME
              value: "eth0"
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: COMMAND
              value: "bash /tmp/start.sh"
          ports:
            - containerPort: {{ .Values.network.port.mariadb }}
            - containerPort: {{ .Values.network.port.wsrep }}
            - containerPort: {{ .Values.network.port.ist }}
          # a readinessprobe is a much more complex affair with
          # statefulsets, as the container must be "live"
          # before the next stateful member is created
          # and with galera this is problematic
          readinessProbe:
            exec:
              command:
                - python
                - /mariadb-readiness.py
            initialDelaySeconds: 60
          volumeMounts:
            - name: mycnfd
              mountPath: /etc/my.cnf.d
            - name: startsh
              mountPath: /tmp/start.sh
              subPath: start.sh
            - name: bootstrapdb
              mountPath: /tmp/bootstrap-db.sh
              subPath: bootstrap-db.sh
            - name: peerfinder
              mountPath: /tmp/peer-finder.py
              subPath: peer-finder.py
            - name: readiness
              mountPath: /mariadb-readiness.py
              subPath: readiness.py
            - name: charsets
              mountPath: /etc/my.cnf.d/charsets.cnf
              subPath: charsets.cnf
            - name: engine
              mountPath: /etc/my.cnf.d/engine.cnf
              subPath: engine.cnf
            - name: log
              mountPath: /etc/my.cnf.d/log.cnf
              subPath: log.cnf
            - name: mycnf
              mountPath: /etc/my.cnf
              subPath: my.cnf
            - name: networking
              mountPath: /etc/my.cnf.d/networking.cnf
              subPath: networking.cnf
            - name: pid
              mountPath: /etc/my.cnf.d/pid.cnf
              subPath: pid.cnf
            - name: tuning
              mountPath: /etc/my.cnf.d/tuning.cnf
              subPath: tuning.cnf
            - name: wsrep
              mountPath: /etc/my.cnf.d/wsrep.cnf
              subPath: wsrep.cnf
            - name: mysql-data
              mountPath: /var/lib/mysql
      volumes:
        - name: mycnfd
          emptyDir: {}
        - name: startsh
          configMap:
            name: mariadb-bin
        - name: bootstrapdb
          configMap:
            name: mariadb-bin
        - name: peerfinder
          configMap:
            name: mariadb-bin
        - name: readiness
          configMap:
            name: mariadb-bin
        - name: charsets
          configMap:
            name: mariadb-etc
        - name: engine
          configMap:
            name: mariadb-etc
        - name: log
          configMap:
            name: mariadb-etc
        - name: mycnf
          configMap:
            name: mariadb-etc
        - name: networking
          configMap:
            name: mariadb-etc
        - name: pid
          configMap:
            name: mariadb-etc
        - name: tuning
          configMap:
            name: mariadb-etc
        - name: wsrep
          configMap:
            name: mariadb-etc
{{- if .Values.development.enabled }}
        - name: mysql-data
          hostPath:
            path: {{ .Values.development.storage_path }}
{{- else }}
  volumeClaimTemplates:
  - metadata:
      name: mysql-data
      annotations:
        {{ .Values.volume.class_path }}: {{ .Values.volume.class_name }}
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: {{ .Values.volume.size }}
{{- end }}
