# Copyright 2017 The Openstack-Helm Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

---
apiVersion: batch/v1
kind: Job
metadata:
  name: mariadb-seed
spec:
  template:
    metadata:
      labels:
        app: mariadb
    spec:
      restartPolicy: Never
      nodeSelector:
        {{ .Values.labels.node_selector_key }}: {{ .Values.labels.node_selector_value }}
      containers:
        - name: mariadb-init
          image: {{ .Values.images.mariadb }}
          imagePullPolicy: {{ .Values.images.pull_policy }}
          {{- if .Values.resources.enabled }}
          resources:
            limits:
              cpu: {{ .Values.resources.job.seed.limits.cpu | quote }}
              memory: {{ .Values.resources.job.seed.limits.memory | quote }}
            requests:
              cpu: {{ .Values.resources.job.seed.requests.cpu | quote }}
              memory: {{ .Values.resources.job.seed.requests.memory | quote }}
          {{- end }}
          env:
            - name: INTERFACE_NAME
              value: "eth0"
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: COMMAND
              value: "bash /tmp/seed.sh"
          ports:
            - containerPort: {{ .Values.network.port.mariadb }}
            - containerPort: {{ .Values.network.port.wsrep }}
            - containerPort: {{ .Values.network.port.ist }}
          volumeMounts:
            - name: mycnfd
              mountPath: /etc/my.cnf.d
            - name: seedsh
              mountPath: /tmp/seed.sh
              subPath: seed.sh
            - name: bootstrapdb
              mountPath: /tmp/bootstrap-db.sh
              subPath: bootstrap-db.sh
            - name: peerfinder
              mountPath: /tmp/peer-finder.py
              subPath: peer-finder.py
            - name: charsets
              mountPath: /etc/my.cnf.d/charsets.cnf
              subPath: charsets.cnf
            - name: engine
              mountPath: /etc/my.cnf.d/engine.cnf
              subPath: engine.cnf
            - name: log
              mountPath: /etc/my.cnf.d/log.cnf
              subPath: log.cnf
            - name: mycnf
              mountPath: /etc/my.cnf
              subPath: my.cnf
            - name: networking
              mountPath: /etc/my.cnf.d/networking.cnf
              subPath: networking.cnf
            - name: pid
              mountPath: /etc/my.cnf.d/pid.cnf
              subPath: pid.cnf
            - name: tuning
              mountPath: /etc/my.cnf.d/tuning.cnf
              subPath: tuning.cnf
            - name: wsrep
              mountPath: /etc/my.cnf.d/wsrep.cnf
              subPath: wsrep.cnf
      volumes:
        - name: mycnfd
          emptyDir: {}
        - name: seedsh
          configMap:
            name: mariadb-bin
        - name: bootstrapdb
          configMap:
            name: mariadb-bin
        - name: peerfinder
          configMap:
            name: mariadb-bin
        - name: charsets
          configMap:
            name: mariadb-etc
        - name: engine
          configMap:
            name: mariadb-etc
        - name: log
          configMap:
            name: mariadb-etc
        - name: mycnf
          configMap:
            name: mariadb-etc
        - name: networking
          configMap:
            name: mariadb-etc
        - name: pid
          configMap:
            name: mariadb-etc
        - name: tuning
          configMap:
            name: mariadb-etc
        - name: wsrep
          configMap:
            name: mariadb-etc
