# Copyright 2017 The Openstack-Helm Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

{{- $envAll := . }}
{{- $dependencies := .Values.dependencies }}
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: rabbitmq
spec:
  replicas: {{ .Values.replicas }}
  revisionHistoryLimit: {{ .Values.upgrades.revision_history }}
  strategy:
    type: {{ .Values.upgrades.pod_replacement_strategy }}
    {{ if eq .Values.upgrades.pod_replacement_strategy "RollingUpdate" }}
    rollingUpdate:
      maxUnavailable: {{ .Values.upgrades.rolling_update.max_unavailable }}
      maxSurge: {{ .Values.upgrades.rolling_update.max_surge }}
    {{ end }}  
  template:
    metadata:
      labels:
        app: rabbitmq
      annotations:
        configmap-bin-hash: {{ tuple "configmap-bin.yaml" . | include "helm-toolkit.hash" }}
        configmap-etc-hash: {{ tuple "configmap-etc.yaml" . | include "helm-toolkit.hash" }}
        pod.beta.kubernetes.io/init-containers: '[
{{ tuple $envAll $dependencies | include "helm-toolkit.kubernetes_entrypoint_init_container" | indent 10 }}
        ]'
        # TODO: this needs to be moved to common.
        scheduler.alpha.kubernetes.io/affinity: >
           {
             "podAntiAffinity": {
               "preferredDuringSchedulingIgnoredDuringExecution": [{
                 "labelSelector": {
                   "matchExpressions": [{
                     "key": "app",
                     "operator": "In",
                     "values":["rabbitmq"]
                   }]
                 },
               "topologyKey": "kubernetes.io/hostname",
               "weight": 10
               }]
             }
           }
    spec:
      nodeSelector:
        {{ .Values.labels.node_selector_key }}: {{ .Values.labels.node_selector_value }}
      volumes:
        - name: rabbitmq-emptydir
          emptyDir: {}
        - name: rabbitmq-bin
          configMap:
            name: rabbitmq-bin
        - name: rabbitmq-etc
          configMap:
            name: rabbitmq-etc
      containers:
        - name: rabbitmq
          image: {{ .Values.images.rabbitmq }}
          {{- if .Values.resources.enabled }}  
          resources:
            limits:
              cpu: {{ .Values.resources.api.limits.cpu | quote }}
              memory: {{ .Values.resources.api.limits.memory | quote }}
            requests:
              cpu: {{ .Values.resources.api.requests.cpu | quote }}
              memory: {{ .Values.resources.api.requests.memory | quote }}
          {{- end }}
          command:
          - bash
          - /scripts/start.sh
          env:
          - name: RABBITMQ_POD_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
          readinessProbe:
            timeoutSeconds: {{ .Values.probes_timeout }}
            exec:
              command:
              - bash
              - /scripts/rabbitmq-readiness.sh
          livenessProbe:
            initialDelaySeconds: {{ .Values.probes_delay }}
            timeoutSeconds: {{ .Values.probes_timeout }}
            exec:
              command:
              - bash
              - /scripts/rabbitmq-liveness.sh
          volumeMounts:
            - name: rabbitmq-emptydir
              mountPath: /var/lib/rabbitmq
            - name: rabbitmq-bin
              mountPath: /scripts
            - name: rabbitmq-etc
              mountPath: /etc/rabbitmq/enabled_plugins
              subPath: enabled_plugins
            - name: rabbitmq-etc
              mountPath: /etc/rabbitmq/erlang.cookie
              subPath: erlang.cookie
            - name: rabbitmq-etc
              mountPath: /etc/rabbitmq/rabbitmq-env.conf
              subPath: rabbitmq-env.conf
            - name: rabbitmq-etc
              mountPath: /etc/rabbitmq/rabbitmq.config
              subPath: rabbitmq.config
