# Copyright 2017 The Openstack-Helm Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Default values for keystone.
# This is a YAML-formatted file.
# Declare name/value pairs to be passed into your templates.
# name: value

replicas: 1

labels:
  node_selector_key: openstack-control-plane
  node_selector_value: enabled

images:
  db_init: quay.io/stackanetes/stackanetes-kolla-toolbox:newton
  db_sync: quay.io/stackanetes/stackanetes-keystone-api:newton
  api: quay.io/stackanetes/stackanetes-keystone-api:newton
  dep_check: quay.io/stackanetes/kubernetes-entrypoint:v0.1.0
  pull_policy: "IfNotPresent"

upgrades:
  revision_history: 3
  pod_replacement_strategy: RollingUpdate
  rolling_update:
    max_unavailable: 1
    max_surge: 3

keystone:
  version: v3
  scheme: http
  admin_region_name: RegionOne
  admin_user: admin
  admin_password: password
  admin_project_name: admin

api:
  default:
    debug: false
  token:
    provider: uuid

network:
  port:
    admin: 35357
    public: 5000
  # alanmeadows(TODO): I seem unable to use {{ .IP }} here
  # but it does work for wsrep.conf in mariadb, I have spent
  # time trying to figure this out am completely stumped
  #
  # helm --debug --dry-run shows me that the config map
  # contains {{ .IP }} but its simply translated by K8s
  # to ""
  ip_address: "0.0.0.0"

database:
  port: 3306
  root_user: root
  root_password: password
  keystone_database_name: keystone
  keystone_password: password
  keystone_user: keystone

dependencies:
  api:
    jobs:
    - mariadb-seed
    - keystone-db-sync
    service:
    - mariadb
  db_sync:
    jobs:
    - keystone-db-init
    - mariadb-seed
    service:
    - mariadb
  init:
    jobs:
    - mariadb-seed
    service:
    - mariadb

resources:
  enabled: false
  api:
    limits:
      memory: "128Mi"
      cpu: "500m"
    requests:
      memory: "128Mi"
      cpu: "500m"
  jobs:
    db_sync:
      limits:
        memory: "128Mi"
        cpu: "500m"
      requests:
        memory: "128Mi"
        cpu: "500m"
    init:
      limits:
        memory: "128Mi"
        cpu: "500m"
      requests:
        memory: "128Mi"
        cpu: "500m"

# typically overriden by environmental
# values, but should include all endpoints
# required by this chart
endpoints:
  keystone:
    hosts:
      default: keystone-api
    path: /v3
    type: identity
    scheme: 'http'
    port:
        admin: 35357
        public: 5000
