apiVersion: v1
kind: ConfigMap
metadata:
  name: horizon-etc
data:
  horizon.conf: |
{{ tuple "etc/_horizon.conf.tpl" . | include "helm-toolkit.template" | indent 4 }}
  local_settings: |
{{ tuple "etc/_local_settings.tpl" . | include "helm-toolkit.template" | indent 4 }}
